### ISSUE TITLE
Table 'nosto_tagging_product_queue' doesn't exist

### ISSUE THREAD

**Issue by cdiacon-img** [Nosto/nosto-magento2#602]
**Magento 2 version(s) used**: 2.3.2
**Extension version(s) affected**: 3.10.0

**Description**  
Getting this error when run the indexer bin/magento index:reindex nosto_product_sync

**How to reproduce**  
Install V3.10.0 and run the command line indexer 
see the error
Base table or view not found

**Magento 2 mode**
- [ X] Developer 
- [ X] Production

**Full page cache**
- [ X] Enabled 
- [ ] Disabled

**Nosto indexer mode**
- [ X] Update On Save  
- [ ] Update By Schedule

Please check the schema upgrade script it's not creating this table at all.
https://github.com/Nosto/nosto-magento2/issues/507

**Comment by olsi-qose** [comment]
Hi @cdiacon-img, was it a fresh new installation of the module. Or upgrade from another version of the module?

**Comment by cdiacon-img** [comment]
@olsi-qose this was an upgrade from V3.8.6, but I remember also we tried to install one of the RC versions 
4.0.0-rc1, do you think that this may be the case?

**Comment by supercid** [comment]
Hi @cdiacon-img,
The RC versions no longer have the `nosto_tagging_product_queue` table. The indexer has been split in two and have another table name and structure.
I suggest you (remove the module)[https://github.com/Nosto/nosto-magento2/wiki/Uninstalling] and try to re-install it.
What could have happened is that when "downgrading" from `4.0.0-RC` to `3.10.0`, the command `setup:upgrade` to update/create tables wasn't executed, since there's a comparison where the version should be higher in order to create/update tables.

Let us know how it goes.

**Comment by cdiacon-img** [comment]
@supercid 
Yes, that was the exact case the upgrade script was not executed, removing/installing did the job. Thanks.
